// this file is autogenerated by react-intl Babel plugin
// from defaultMessages({}) function calls in React components
// (do not edit this file, the changes to it will be lost)
module.exports = 
{
}