// `messages/en.json` file is autogenerated by react-intl Babel plugin
// from defaultMessages({}) function calls in React components
// (do not edit that file, the changes to it will be lost)

import countries from './countries/en'
import messages  from './messages/en'
import generate  from './common'

export default generate(messages, countries)