// `messages/en.json` file is autogenerated by react-intl Babel plugin
// from defaultMessages({}) function calls in React components
// (do not edit that file, the changes to it will be lost)

import countries from './countries/en'
import messages  from './messages/en'

const all = {}

for (let key of Object.keys(messages))
{
	all[key] = messages[key]
}

for (let key of Object.keys(countries))
{
	all[`country.${key}`] = countries[key]
}

export default all